config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root 'home#index'
  resources :posts
  resources :comments
  resources :authors
  resources :users, only: [:show]

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :posts
  belongs_to :user
	validates :name, :email, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
validates :text, presence: true
belongs_to :post

scope :published_post, -> {where(published: true)}
end

app/models/post.rb
class Post < ActiveRecord::Base
validates :text, presence: true
has_many :comments
belongs_to :author

scope :published, -> {where(published: true)}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :trackable, :validatable

  has_many :authors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!
  def index
  @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_path, alert: "Usunięto."
  end

  def new
  @author = Author.new
  end

  def create
     @author = Author.new(author_params)
      if @author.save
      redirect_to authors_path, notice: "Dodano."
    else
      render 'new'
    end
  end  

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      redirect_to authors_path
    else
      render :edit
    end
  end


  private
  def author_params
    params.require(:author).permit(:name, :email, :user_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path, alert: "Usunięto."
  end

  def new
  @comment = Comment.new
  @post_id = params[:id]
  end

  def create
     @comment = Comment.new(comment_params)
      if @comment.save
      redirect_to comments_path, notice: "Dodano."
    else
      render 'new'
    end
  end  

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to comments_path
    else
      render :edit
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
 @zmienna = 'Cześć' #zmienna instancji
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :user_signed_in, only: [:destroy, :edit]
  def index
  @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, alert: "Usunięto."
  end

  def new
  @post = Post.new
  end

 def create
     @post = Post.new(post_params)
      if @post.save
      redirect_to posts_path, notice: "Dodano."
    else
      render 'new'
    end
  end  

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end
  
  private
  def post_params
    params.require(:post).permit(:text)
  end

  private 
  def user_signed_in
  unless current_user and (current_user.id != params[:id].to_i)
  redirect_to posts_path, alert: "To nie twoje konto"
  end
  true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :make_sure_its_mine

def show
@user=current_user
end

private 
def make_sure_its_mine
unless current_user.id == params[:id].to_i
redirect_to root_url, alert: "To nie twoje konto"
end
true
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/edit.html.erb
<h1>Edytuj mail</h1>
<%= form_for(@author) do |f| %>
<% @author.errors.full_messages.each do |err| %> 
 <li><%= err %></li> 
<% end %>
  <%= f.label "stary mail" %>
  <%= f.text_field :email %>
  <%= f.submit "Edytuj!" %>
  <% end %>

app/views/authors/index.html.haml
%h1
  Lista autorów
=link_to "dodaj", new_author_path

%ul
  -@authors.each do |author|
    %li
      =author.name
      =link_to "edytuj", edit_author_path(id: author.id)
      =link_to "update", author_path(id: author.id), method: :patch
      =link_to "usuń", author_path(id: author.id), method: :delete

app/views/authors/new.html.erb
<h1>Dodaj autora</h1>
<%= form_for(@author) do |f| %>
<% @author.errors.full_messages.each do |err| %> 
 <li><%= err %></li> 
<% end %>
  <%= f.label "podaj imie" %>
  <%= f.text_field :name %>
  <%= f.label "podaj email" %>
  <%= f.text_field :email %>
  <%= f.hidden_field :user_id, value: current_user.id%>
  
  <%= f.submit "Dodaj!" %>
  <% end %>

app/views/authors/show.html.erb
<h1>Autor</h1>
<%= @author.name%>

app/views/comments/edit.html.erb
<h1>Edytuj komentarz</h1>
<%= form_for(@comment) do |f| %>
<% @comment.errors.full_messages.each do |err| %> 
 <li><%= err %></li> 
<% end %>
  <%= f.label "tresc komentarza" %>
  <%= f.text_field :text %>
  <%= f.submit "Edytuj!" %>
  <% end %>

app/views/comments/index.html.haml
%h1
  Lista komentarzy
=link_to "dodaj", new_comment_path
%ul
  -@comments.each do |comment|
    %li
      =comment.text
      -if comment.post
        = comment.post.text
      = link_to "edytuj", edit_comment_path(id: comment.id)
      = link_to "usuń", comment_path(id: comment.id), method: :delete

app/views/comments/new.html.erb
<h1>Dodaj komentarz</h1>
<%= form_for(@comment) do |f| %>
<% @comment.errors.full_messages.each do |err| %> 
 <li><%= err %></li> 
<% end %>
  <%= f.label "tresc komentarza" %>
  <%= f.text_field :text %>
  <%= f.hidden_field :post_id, value: @post_id %>
  <%= f.submit "Dodaj!" %>

  <% end %>

app/views/comments/show.html.erb
<h1>Jeden komentarz</h1>
<%= @comment.text%>

app/views/home/index.html.erb
<% if current_user%>
<h1>Bzzz...<%= current_user.email%></h1>
<%=link_to "wyloguj się", destroy_user_session_path, method: :delete%>
<%= link_to "pokaż panel", user_path(current_user.id) %>
<%else%>
<h1>Cześć nieznajomy</h1>
<%= link_to "zarejestruj sie", new_user_registration_path%>
<%= link_to "zaloguj się", new_user_session_path%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
  <% if alert %>
  <p>Uwaga: <%= alert %></p>
  <% elsif notice%>
  <p>Jest git. <%= notice %></p>
  <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edytuj post</h1>
<%= form_for(@post) do |f| %>
<% @post.errors.full_messages.each do |err| %> 
 <li><%= err %></li> 
<% end %>
  <%= f.label "tresc posta" %>
  <%= f.text_field :text %>
  <%= f.submit "Edytuj!", :class => "btn btn-default" %>
  <% end %>

app/views/posts/index.html.haml
%h1
  Lista postów
=link_to "dodaj", new_post_path
%ul
  -@posts.each do |post|
    %li
      =post.text
        
      .button.btn.btn-default
        =link_to "Edytuj", edit_post_path(id: post.id), role: "button"
      .button.btn.btn-default
        = link_to "usuń", post_path(id: post.id), method: :delete, role: "button"
      .button.btn.btn-default
        =link_to "dodaj komentarz", new_comment_path(id: post.id), role: "button"
      /%a.button.btn.btn-primary{role: "button", href: edit_post_path(id: post.id)} Edytuj
      /%a.button.btn.btn-warning{role: "button", href: post_path(id: post.id), method: :delete} Usuń
      /%a.button.btn.btn-default{role: "button", href: new_comment_path(id: post.comment.id)} Dodaj komentarz

app/views/posts/new.html.erb
<h1>Dodaj post</h1>
<%= form_for(@post) do |f| %>
<% @post.errors.full_messages.each do |err| %> 
 <li><%= err %></li> 
<% end %>
  <%= f.label "tresc posta" %>
  <%= f.text_field :text %>
  <%= f.submit "Dodaj!" %>
  <% end %>

app/views/posts/show.html.erb
<h1>Jeden post</h1>
<%= @post.text%>

app/views/users/show.html.haml
%h1 panel usera
%h3=@user.email
%hr
%ul
  -@user.authors.each do |author|
    %li
      =author.name
      =link_to "pokaz", author_path(author.id)